import { setGlobalContext_prodBuildEntry } from 'vike/__internal';

/*! virtual:vike:server:constantsGlobalThis [vike:pluginModuleBanner] */
globalThis.__VIKE__IS_DEV = false;
globalThis.__VIKE__IS_CLIENT = false;
globalThis.__VIKE__IS_DEBUG = false;

/*! virtual:vike:global-entry:server [vike:pluginModuleBanner] */
// Generated by Vike

const pageFilesLazy = {};
const pageFilesEager = {};
const pageFilesExportNamesLazy = {};
const pageFilesExportNamesEager = {};
const pageFilesList = [];
const neverLoaded = {};
const pageConfigsSerialized = [
  {
    pageId: "/pages/faq",
    isErrorPage: undefined,
    routeFilesystem: {"routeString":"/faq","definedAtLocation":"/pages/faq/"},
    loadVirtualFilePageEntry: () => ({ moduleId: "virtual:vike:page-entry:server:/pages/faq", moduleExportsPromise: import('./entries/pages_faq.mjs') }),
    configValuesSerialized: {
      ["isClientRuntimeLoaded"]: {
        type: "computed",
        definedAtData: null,
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
      ["clientRouting"]: {
        type: "standard",
        definedAtData: {"filePathToShowToUser":"vike-react/config","fileExportPathToShowToUser":["default","clientRouting"]},
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
    },
  },
  {
    pageId: "/pages/index",
    isErrorPage: undefined,
    routeFilesystem: {"routeString":"/","definedAtLocation":"/pages/index/"},
    loadVirtualFilePageEntry: () => ({ moduleId: "virtual:vike:page-entry:server:/pages/index", moduleExportsPromise: import('./entries/pages_index.mjs') }),
    configValuesSerialized: {
      ["isClientRuntimeLoaded"]: {
        type: "computed",
        definedAtData: null,
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
      ["clientRouting"]: {
        type: "standard",
        definedAtData: {"filePathToShowToUser":"vike-react/config","fileExportPathToShowToUser":["default","clientRouting"]},
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
    },
  },
  {
    pageId: "/pages/products",
    isErrorPage: undefined,
    routeFilesystem: {"routeString":"/products","definedAtLocation":"/pages/products/"},
    loadVirtualFilePageEntry: () => ({ moduleId: "virtual:vike:page-entry:server:/pages/products", moduleExportsPromise: import('./entries/pages_products.mjs') }),
    configValuesSerialized: {
      ["isClientRuntimeLoaded"]: {
        type: "computed",
        definedAtData: null,
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
      ["clientRouting"]: {
        type: "standard",
        definedAtData: {"filePathToShowToUser":"vike-react/config","fileExportPathToShowToUser":["default","clientRouting"]},
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
    },
  },
  {
    pageId: "/pages/products/@id",
    isErrorPage: undefined,
    routeFilesystem: {"routeString":"/products/@id","definedAtLocation":"/pages/products/@id/"},
    loadVirtualFilePageEntry: () => ({ moduleId: "virtual:vike:page-entry:server:/pages/products/@id", moduleExportsPromise: import('./entries/pages_products_-id.mjs') }),
    configValuesSerialized: {
      ["isClientRuntimeLoaded"]: {
        type: "computed",
        definedAtData: null,
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
      ["clientRouting"]: {
        type: "standard",
        definedAtData: {"filePathToShowToUser":"vike-react/config","fileExportPathToShowToUser":["default","clientRouting"]},
        valueSerialized: {
          type: "js-serialized",
          value: true,
        },
      },
    },
  },
];
const pageConfigGlobalSerialized = {
  configValuesSerialized: {
  },
};

const pageFilesLazyIsomorph1 = /* #__PURE__ */ Object.assign({});
const pageFilesLazyIsomorph = {...pageFilesLazyIsomorph1};
pageFilesLazy['.page'] = pageFilesLazyIsomorph;
const pageFilesExportNamesEagerIsomorph1 = /* #__PURE__ */ Object.assign({});
const pageFilesExportNamesEagerIsomorph = {...pageFilesExportNamesEagerIsomorph1};
pageFilesExportNamesEager['.page'] = pageFilesExportNamesEagerIsomorph;
const pageFilesLazyServer1 = /* #__PURE__ */ Object.assign({});
const pageFilesLazyServer = {...pageFilesLazyServer1};
pageFilesLazy['.page.server'] = pageFilesLazyServer;
const pageFilesExportNamesEagerServer1 = /* #__PURE__ */ Object.assign({});
const pageFilesExportNamesEagerServer = {...pageFilesExportNamesEagerServer1};
pageFilesExportNamesEager['.page.server'] = pageFilesExportNamesEagerServer;
const pageFilesEagerRoute1 = /* #__PURE__ */ Object.assign({});
const pageFilesEagerRoute = {...pageFilesEagerRoute1};
pageFilesEager['.page.route'] = pageFilesEagerRoute;
const pageFilesExportNamesEagerClient1 = /* #__PURE__ */ Object.assign({});
const pageFilesExportNamesEagerClient = {...pageFilesExportNamesEagerClient1};
pageFilesExportNamesEager['.page.client'] = pageFilesExportNamesEagerClient;

const virtualFileExportsGlobalEntry = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  neverLoaded,
  pageConfigGlobalSerialized,
  pageConfigsSerialized,
  pageFilesEager,
  pageFilesExportNamesEager,
  pageFilesExportNamesLazy,
  pageFilesLazy,
  pageFilesList
}, Symbol.toStringTag, { value: 'Module' }));

/*! virtual:@brillout/vite-plugin-server-entry:serverEntry [vike:pluginModuleBanner] */
// Generated by https://github.com/brillout/vite-plugin-server-entry
  {
    const assetsManifest = {
  "_chunk-BAh4JXMg.js": {
    "file": "assets/chunks/chunk-BAh4JXMg.js",
    "name": "Loading",
    "css": [
      "assets/static/index-bca1542f.Cp0TlRf4.css"
    ]
  },
  "_chunk-CLr09eor.js": {
    "file": "assets/chunks/chunk-CLr09eor.js",
    "name": "arrow-right",
    "imports": [
      "_chunk-BAh4JXMg.js"
    ]
  },
  "_index-bca1542f.Cp0TlRf4.css": {
    "file": "assets/static/index-bca1542f.Cp0TlRf4.css",
    "src": "_index-bca1542f.Cp0TlRf4.css"
  },
  "node_modules/vike/dist/client/runtime-client-routing/entry.js": {
    "file": "assets/entries/entry-client-routing.DbeHUpiI.js",
    "name": "entries/entry-client-routing",
    "src": "node_modules/vike/dist/client/runtime-client-routing/entry.js",
    "isEntry": true,
    "dynamicImports": [
      "virtual:vike:page-entry:client:/pages/faq",
      "virtual:vike:page-entry:client:/pages/index",
      "virtual:vike:page-entry:client:/pages/products",
      "virtual:vike:page-entry:client:/pages/products/@id"
    ]
  },
  "virtual:vike:page-entry:client:/pages/faq": {
    "file": "assets/entries/pages_faq.SQcmHGcL.js",
    "name": "entries/pages/faq",
    "src": "virtual:vike:page-entry:client:/pages/faq",
    "isEntry": true,
    "isDynamicEntry": true,
    "imports": [
      "_chunk-BAh4JXMg.js"
    ],
    "css": [
      "assets/static/index-bca1542f.Cp0TlRf4.css"
    ]
  },
  "virtual:vike:page-entry:client:/pages/index": {
    "file": "assets/entries/pages_index.CugDeiIb.js",
    "name": "entries/pages/index",
    "src": "virtual:vike:page-entry:client:/pages/index",
    "isEntry": true,
    "isDynamicEntry": true,
    "imports": [
      "_chunk-BAh4JXMg.js",
      "_chunk-CLr09eor.js"
    ],
    "css": [
      "assets/static/index-bca1542f.Cp0TlRf4.css"
    ]
  },
  "virtual:vike:page-entry:client:/pages/products": {
    "file": "assets/entries/pages_products.BDmt6uQz.js",
    "name": "entries/pages/products",
    "src": "virtual:vike:page-entry:client:/pages/products",
    "isEntry": true,
    "isDynamicEntry": true,
    "imports": [
      "_chunk-BAh4JXMg.js",
      "_chunk-CLr09eor.js"
    ],
    "css": [
      "assets/static/index-bca1542f.Cp0TlRf4.css"
    ]
  },
  "virtual:vike:page-entry:client:/pages/products/@id": {
    "file": "assets/entries/pages_products_-id.BYGL2qc5.js",
    "name": "entries/pages/products/@id",
    "src": "virtual:vike:page-entry:client:/pages/products/@id",
    "isEntry": true,
    "isDynamicEntry": true,
    "imports": [
      "_chunk-BAh4JXMg.js"
    ],
    "css": [
      "assets/static/index-bca1542f.Cp0TlRf4.css"
    ]
  }
};
    const buildInfo = {
  "versionAtBuildTime": "0.4.249",
  "usesClientRouter": false,
  "viteConfigRuntime": {
    "root": "/home/runner/work/enigmabox/enigmabox",
    "build": {
      "outDir": "/home/runner/work/enigmabox/enigmabox/dist/"
    },
    "_baseViteOriginal": "/",
    "vitePluginServerEntry": {}
  }
};
    setGlobalContext_prodBuildEntry({
      virtualFileExportsGlobalEntry,
      assetsManifest,
      buildInfo,
    });
  }
